// Copyright 2026 Joshua Rich <joshua.rich@gmail.com>.
// SPDX-License-Identifier: 	AGPL-3.0-or-later

package assets

import (
	"embed"
	"encoding/json"
	"fmt"
	"io/fs"
	"maps"
	"net/http"
	"path"
	"path/filepath"
	"slices"
	"time"

	"github.com/go-chi/chi/v5"
)

// assetMap maps a plain, unhashed file to it's hashed version stored in an [fs.FS]. This is used for serving hashed
// assets. Unhashed files in the FS can be accessed directly and are not indexed in the assetMap.
var assetMap map[string]string

type metafile struct {
	Outputs map[string]struct {
		EntryPoint string              `json:"entryPoint"`
		Inputs     map[string]struct{} `json:"inputs"`
	} `json:"outputs"`
}

// hashedFileExtensions is the list of file extensions of files to add to the global assetMap.
var hashedFileExtensions = []string{".woff2"}

// GenerateAssetMap reads a metadata file generated by esbuild and creates a map of the original file to its hashed
// version.
func GenerateAssetMap(fsys fs.FS, metafilePath string) error {
	b, err := fs.ReadFile(fsys, metafilePath)
	if err != nil {
		return fmt.Errorf("read metdata file: %w", err)
	}
	var m metafile
	if err := json.Unmarshal(b, &m); err != nil {
		return fmt.Errorf("unmarshal metadata: %w", err)
	}
	out := map[string]string{}
	for outPath, o := range m.Outputs {
		if o.EntryPoint != "" {
			// Store the output file's entrypoint -> file mapping.
			out[o.EntryPoint] = filepath.Join("/files/dist/", filepath.Base(outPath))
		}
		for inPath := range o.Inputs {
			if slices.Contains(hashedFileExtensions, filepath.Ext(inPath)) {
				// Store the hashed file's entrypoint -> file mapping.
				out[filepath.Base(inPath)] = filepath.Base(outPath)
			}
		}
	}

	if assetMap == nil {
		// Initialize the global assetMap if not already initialized.
		assetMap = make(map[string]string)
	}
	// Copy the new mappings.
	maps.Copy(assetMap, out)
	return nil
}

// AssetPath returns the hashed asset path for the given file.
func AssetPath(path string) string {
	if assetMap == nil {
		return ""
	}
	if asset, ok := assetMap[path]; ok {
		return asset
	}
	return ""
}

// ServeFiles returns an http.Handler that serves files from the given [embed.FS].
func ServeFiles(fsys embed.FS, prefix string) http.Handler {
	return http.HandlerFunc(func(res http.ResponseWriter, req *http.Request) {
		if req.Method != http.MethodGet && req.Method != http.MethodHead {
			http.Error(res, "method not allowed", http.StatusMethodNotAllowed)
			return
		}

		var path string
		switch {
		case chi.URLParam(req, "*") != "":
			// Get the path from the URL parameter.
			path = filepath.Join(prefix, chi.URLParam(req, "*"))
		default:
			// If there is no URL parameter, assume the whole path is a file in the embedded FS.
			path = filepath.Join(prefix, req.URL.Path)
		}

		f, err := fsys.Open(path)
		if err != nil {
			http.NotFound(res, req)
			return
		}
		defer f.Close()

		// Set appropriate headers.
		res.Header().Set("Cache-Control", "public, max-age=31536000, immutable")
		res.Header().Set("Content-Type", contentTypeFor(path))
		res.Header().Set("Cross-Origin-Resource-Policy", "cross-origin")

		// Serve the file.
		if rs, ok := f.(interface {
			fs.File
			Seek(offset int64, whence int) (int64, error)
		}); ok {
			http.ServeContent(res, req, path, time.Time{}, rs)
			return
		}
		// Fallback for files that don't support seeking (rare with embed.FS, but kept for safety).
		data, err := fsys.ReadFile(path)
		if err != nil {
			http.Error(res, "internal error", http.StatusInternalServerError)
			return
		}
		res.Write(data)
	})
}

func contentTypeFor(p string) string {
	switch path.Ext(p) {
	case ".js", ".mjs":
		return "text/javascript; charset=utf-8"
	case ".css":
		return "text/css; charset=utf-8"
	case ".svg":
		return "image/svg+xml"
	case ".png":
		return "image/png"
	case ".webp":
		return "image/webp"
	case ".jpg", ".jpeg":
		return "image/jpeg"
	case ".gif":
		return "image/gif"
	case ".woff2":
		return "font/woff2"
	case ".json":
		return "application/json; charset=utf-8"
	case ".txt":
		return "text/plain; charset=utf-8"
	case ".ico":
		return "image/vnd.microsoft.icon"
	default:
		return "application/octet-stream"
	}
}
